[profile.default]
src = "contracts"
out = "foundry/out"
libs = ["lib"]
test = "foundry/test"
remappings = ["@openzeppelin=lib/openzeppelin-contracts/contracts"]

[profile.optimized]
optimizer_runs = 1000
// Generic update 28
// Generic update 37
// Generic update 14
